### ISSUE TITLE
OpenFOAM7 bugs

### ISSUE THREAD

**Issue by ZSHtju** [NHERI-SimCenter/TurbulenceInflowTool#31]
The code can not run with OpenFOAM7, it seems the bugs fixed in OpenFOAM6 are not implemented in OpenFOAM7.

**Comment by pmackenz** [comment]
> The code can not run with OpenFOAM7, it seems the bugs fixed in OpenFOAM6 are not implemented in OpenFOAM7.

Can you please provide some more specifics on the issue so we can reproduce it?  We would need input files and a description of the steps taken that lead to the problem.  Thanks

**Comment by ZSHtju** [comment]
Hi,
Thanks for the reply.  I have tried the latest code, it works perfectly in OpenFOAM 7 now.
I think this issue can be closed.
Many thanks.
